### ISSUE TITLE
Broke Ubuntu release upgrade from 22.04.5 to 24.04.1

### ISSUE THREAD

**Issue by hantsaniala** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#28]
First, thanks a lot for this script. Next, running the following command return the following error:

```sh
$ do-release-upgrade
...
cat: /tmp/opera.timestamp: No such file or directory
sh: 1: [: -ne: argument expected
rm: cannot remove '/tmp/opera.timestamp': No such file or directory
Exception during pm.DoInstall():  E:Problem executing scripts DPkg::Post-Invoke 'if [ `stat -c %Z $(readlink -f $(which opera))` -ne `cat /tmp/opera.timestamp` ]; then /root/.scripts/fix-opera.sh; fi; rm /tmp/opera.timestamp', E:Sub-process returned an error code

Traceback (most recent call last):
  File "/tmp/ubuntu-release-upgrader-rqmv_7di/noble", line 8, in <module>
    sys.exit(main())
  File "/tmp/ubuntu-release-upgrader-rqmv_7di/DistUpgrade/DistUpgradeMain.py", line 241, in main
    if app.run():
  File "/tmp/ubuntu-release-upgrader-rqmv_7di/DistUpgrade/DistUpgradeController.py", line 2662, in run
    return self.fullUpgrade()
  File "/tmp/ubuntu-release-upgrader-rqmv_7di/DistUpgrade/DistUpgradeController.py", line 2467, in fullUpgrade
    if not self.doPostInitialUpdate():
  File "/tmp/ubuntu-release-upgrader-rqmv_7di/DistUpgrade/DistUpgradeController.py", line 1438, in doPostInitialUpdate
    self.quirks.run("PostInitialUpdate")
  File "/tmp/ubuntu-release-upgrader-rqmv_7di/DistUpgrade/DistUpgradeQuirks.py", line 102, in run
    func()
  File "/tmp/ubuntu-release-upgrader-rqmv_7di/DistUpgrade/DistUpgradeQuirks.py", line 135, in noblePostInitialUpdate
    self._maybe_prevent_flatpak_auto_removal()
  File "/tmp/ubuntu-release-upgrader-rqmv_7di/DistUpgrade/DistUpgradeQuirks.py", line 538, in _maybe_prevent_flatpak_auto_removal
    self.controller.cache.commit(
  File "/tmp/ubuntu-release-upgrader-rqmv_7di/DistUpgrade/DistUpgradeCache.py", line 328, in commit
    apt.Cache.commit(self, fprogress, iprogress)
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 668, in commit
    raise SystemError("installArchives() failed")
SystemError: installArchives() failed
```

Opera version: 113.0.5230.62
Ubuntu version:  22.04.5

Temporary solution: uninstall it before doing `do-release-upgrade`.

**Comment by yanisalfian** [comment]
Hi, just wanna tell that on my environment this issue has been resolved with reinstalling latest version of this package. 

Thank you

**Comment by smirff** [comment]
`DPkg::Pre-Invoke {"stat -L -c %Z %22$(which opera)%22 >/tmp/opera.timestamp 2>/dev/null || echo 0 >/tmp/opera.timestamp";};`
`DPkg::Post-Invoke {"OPERA_PATH=%22$(which opera)%22 || exit 0 ; if [ -e %22$OPERA_PATH%22 -a $(stat -L -c %Z %22$OPERA_PATH%22 2>/dev/null || echo -1 ) != $(cat /tmp/opera.timestamp 2>/dev/null || echo 0 ) ]; then /root/.scripts/fix-opera.sh; fi; rm -f /tmp/opera.timestamp";};`
